Repository mirumee/ariadne, pull requests merged in 2018-12, with the labels that each got.

#72 Refactor resolvers implementation
  CHANGELOG.md
  README.md
  ariadne/__init__.py
  ariadne/executable_schema.py
  ariadne/resolvers.py
  ariadne/scalars.py
  ariadne/simple_server.py
  ariadne/types.py
  ariadne/utils.py
  ariadne/wsgi_middleware.py
  docs/custom-server.rst
  docs/introduction.rst
  docs/modularization.rst
  docs/mutations.rst
  docs/resolvers.rst
  docs/scalars.rst
  docs/wsgi-middleware.rst
  requirements.txt
  setup.py
  tests/conftest.py
  tests/test_case_convertion_util.py
  tests/test_custom_scalars.py
  tests/test_enums.py
  tests/test_fallback_resolvers.py
  tests/test_introspection.py
  tests/test_modularization.py
  tests/test_mutations.py
  tests/test_queries.py
  tests/test_resolver_map.py
  tests/test_start_simple_server.py
  tests/wsgi_middleware/conftest.py
  tests/wsgi_middleware/test_custom_middleware.py
  tests/wsgi_middleware/test_initialization.py
  tests/wsgi_middleware/test_request_dispatching.py
Labels: enhancement, in progress, roadmap

#75 Enable schema loading from file or directory
  CHANGELOG.md
  ariadne/__init__.py
  ariadne/exceptions.py
  ariadne/load_schema.py
  tests/test_schema_file_load.py
Labels: enhancement

#78 Add readthedocs.yml config to force py3.6 for docs builds
  readthedocs.yml
Labels: bug, docs

#79 Fix type definition for Resolver
  ariadne/types.py
Labels: bug

#81 Improve docs after recent changes
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/custom-server.rst
  docs/introduction.rst
  docs/modularization.rst
  docs/mutations.rst
  docs/resolvers.rst
  docs/scalars.rst
  docs/wsgi-middleware.rst
Labels: docs, enhancement

#82 Fix docs badge and link in readme
  README.md
Labels: docs, meta

#84 Link to logo in master docs version
  README.md
Labels: enhancement, meta

#83 Bump python package version number to 0.2.0b1
  setup.py
Labels: meta
