Repository mirumee/ariadne, pull requests merged in 2018-10, with the labels that each got.

#28 Add GraphQL Playground
  .pylintrc
  .travis.yml
  README.md
  ariadne/__init__.py
  ariadne/constants.py
  ariadne/exceptions.py
  ariadne/wsgi_middleware.py
  tests/wsgi_middleware/__init__.py
  tests/wsgi_middleware/conftest.py
  tests/wsgi_middleware/snapshots/__init__.py
  tests/wsgi_middleware/snapshots/snap_test_custom_middleware.py
  tests/wsgi_middleware/snapshots/snap_test_playground.py
  tests/wsgi_middleware/snapshots/snap_test_query_execution.py
  tests/wsgi_middleware/snapshots/snap_test_request_data_reading.py
  tests/wsgi_middleware/test_custom_middleware.py
  tests/wsgi_middleware/test_http_error_handling.py
  tests/wsgi_middleware/test_initialization.py
  tests/wsgi_middleware/test_playground.py
  tests/wsgi_middleware/test_query_execution.py
  tests/wsgi_middleware/test_request_data_reading.py
  tests/wsgi_middleware/test_request_dispatching.py
  tests/wsgi_middleware/test_simple_server.py
Labels: enhancement, roadmap

#42 Update playground to 1.7.8
  ariadne/constants.py
  tests/wsgi_middleware/snapshots/snap_test_playground.py
Labels: bug

#41 Add basic documentation
  docs/Makefile
  docs/_static/hello-world.png
  docs/conf.py
  docs/custom-server.rst
  docs/enums.rst
  docs/error-messaging.rst
  docs/index.rst
  docs/introduction.rst
  docs/make.bat
  docs/modularization.rst
  docs/mutations.rst
  docs/resolvers.rst
  docs/scalars.rst
  docs/wsgi-middleware.rst
Labels: docs, roadmap

#46 Add contributing and coc, update readme
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: enhancement

#49 Rename dev-requirements to requirements-dev
  requirements-dev.in
  requirements-dev.txt
Labels: meta

#50 Add logo to docs and readme
  README.md
  docs/_static/icon.png
  docs/_static/logo-vertical.png
  docs/_static/logo.png
  docs/conf.py
Labels: docs, meta

#52 Add logo page to readme
  README.md
  docs/index.rst
  docs/logo.rst
Labels: meta

#51 Doc tweaks
  CONTRIBUTING.md
  README.md
  docs/conf.py
Labels: docs, enhancement

#53 Set long description content type to markdown
  setup.py
Labels: bug, meta
