Repository mirumee/ariadne, pull requests merged in 2018-11, with the labels that each got.

#58 Define object types for mutations
  docs/mutations.rst
Labels: docs

#59 Bump python requirement to 3.6, add 3.7 to tests matrix and drop 3.5
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  ariadne/executable_schema.py
  docs/index.rst
  setup.py
Labels: enhancement, roadmap

#61 Migrate to graphql-core-next
  CHANGELOG.md
  ariadne/__init__.py
  ariadne/build_schema.py
  ariadne/exceptions.py
  ariadne/executable_schema.py
  ariadne/resolvers.py
  ariadne/wsgi_middleware.py
  docs/resolvers.rst
  docs/scalars.rst
  requirements.txt
  setup.py
  tests/snapshots/snap_test_introspection.py
  tests/test_custom_scalars.py
  tests/test_enums.py
  tests/test_introspection.py
  tests/test_modularization.py
  tests/test_mutations.py
  tests/test_queries.py
  tests/wsgi_middleware/conftest.py
  tests/wsgi_middleware/snapshots/snap_test_query_execution.py
  tests/wsgi_middleware/snapshots/snap_test_request_data_reading.py
  tests/wsgi_middleware/test_custom_middleware.py
  tests/wsgi_middleware/test_query_execution.py
  tests/wsgi_middleware/test_request_dispatching.py
Labels: enhancement, roadmap

#67 Add gql() utility
  CHANGELOG.md
  README.md
  ariadne/__init__.py
  ariadne/utils.py
  docs/introduction.rst
  tests/test_gql_util.py
Labels: docs, enhancement, roadmap

#68 Add simple server util
  CHANGELOG.md
  README.md
  ariadne/__init__.py
  ariadne/utils.py
  docs/introduction.rst
  docs/wsgi-middleware.rst
  tests/test_start_simple_server.py
Labels: enhancement

#71 Fix missing graphql-core references to point to graphql-core-next
  README.md
  docs/conf.py
  docs/scalars.rst
Labels: docs, enhancement, meta

#70 Re-word changelog and make test fixtures little more real-worldly
  CHANGELOG.md
  tests/test_start_simple_server.py
Labels: enhancement
