Repository mirumee/ariadne, pull requests merged in 2019-05, with the labels that each got.

#152 Change custom servers doc to "integrations"
  CHANGELOG.md
  docs/index.rst
  docs/integrations.rst
Labels: docs, enhancement, roadmap

#150 Update graphql-core-next to 1.0.3
  CHANGELOG.md
  README.md
  ariadne/asgi.py
  ariadne/enums.py
  ariadne/format_errors.py
  ariadne/graphql.py
  ariadne/interfaces.py
  ariadne/objects.py
  ariadne/scalars.py
  ariadne/types.py
  ariadne/unions.py
  ariadne/wsgi.py
  docs/index.rst
  requirements.txt
  setup.py
Labels: enhancement

#153 Add name checks for field and source decorators
  CHANGELOG.md
  ariadne/objects.py
  ariadne/subscriptions.py
  tests/test_objects.py
  tests/test_subscriptions.py
Labels: enhancement, roadmap

#155 Update dev requirements
  requirements-dev.in
  requirements-dev.txt
Labels: roadmap

#162 Update documentation of context_for_request method to match definition
  docs/asgi.rst
Labels: docs, enhancement

#163 Update travis config
  .travis.yml
  requirements-dev.in
  requirements-dev.txt
Labels: enhancement, meta, roadmap

#164 Limit test coverage generation to ariadne and tests
  .travis.yml
  tests/test_custom_scalars.py
Labels: enhancement, meta, roadmap

#166 Extend schema types
  CHANGELOG.md
  ariadne/executable_schema.py
  tests/test_modularization.py
Labels: enhancement, roadmap

#168 Support callable context_value and root_value
  CHANGELOG.md
  ariadne/asgi.py
  ariadne/graphql.py
  ariadne/types.py
  ariadne/wsgi.py
  docs/asgi.rst
  docs/integrations.rst
  docs/wsgi.rst
  tests/asgi/test_configuration.py
  tests/conftest.py
  tests/wsgi/snapshots/snap_test_custom_middleware.py
  tests/wsgi/test_configuration.py
  tests/wsgi/test_custom_middleware.py
Labels: docs, enhancement, roadmap

#169 Remove unused extract_data_from_websocket
  ariadne/asgi.py
Labels: enhancement, roadmap

#170 Document integration with Starlette
  docs/integrations.rst
Labels: docs

#157 Error handling improvements
  .pylintrc
  CHANGELOG.md
  ariadne/asgi.py
  ariadne/format_error.py
  ariadne/graphql.py
  ariadne/logger.py
  ariadne/utils.py
  ariadne/wsgi.py
  docs/index.rst
  docs/integrations.rst
  docs/logging.rst
  tests/asgi/__init__.py
  tests/asgi/snapshots/snap_test_query_execution.py
  tests/asgi/test_configuration.py
  tests/asgi/test_query_execution.py
  tests/asgi/test_websockets.py
  tests/conftest.py
  tests/wsgi/test_configuration.py
Labels: bug, enhancement, roadmap

#172 Set default enums values in schema
  CHANGELOG.md
  ariadne/enums.py
  ariadne/executable_schema.py
  tests/test_enums.py
Labels: enhancement, roadmap

#174 Simplify logger configuration
  ariadne/asgi.py
  ariadne/graphql.py
  ariadne/logger.py
  ariadne/wsgi.py
  docs/logging.rst
  tests/asgi/test_configuration.py
  tests/wsgi/test_configuration.py
Labels: docs, enhancement, roadmap

#175 Add ariadne.contrib.django
  .pylintrc
  CHANGELOG.md
  ariadne/contrib/__init__.py
  ariadne/contrib/django/__init__.py
  ariadne/contrib/django/apps.py
  ariadne/contrib/django/scalars.py
  ariadne/contrib/django/templates/ariadne/graphql_playground.html
  ariadne/contrib/django/views.py
  docs/integrations.rst
  requirements-dev.in
  requirements-dev.txt
  tests/django/__init__.py
  tests/django/conftest.py
  tests/django/snapshots/__init__.py
  tests/django/snapshots/snap_test_playground.py
  tests/django/snapshots/snap_test_query_execution.py
  tests/django/test_configuration.py
  tests/django/test_playground.py
  tests/django/test_query_execution.py
  tests/django/test_scalars.py
Labels: docs, enhancement, roadmap

#176 Fix django integration example to mention django app
  docs/integrations.rst
Labels: docs, enhancement

#178 Add py.typed to project
  CHANGELOG.md
  ariadne/py.typed
  setup.py
Labels: meta, roadmap

#181 Update Starlette to 0.12
  ariadne/asgi.py
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: roadmap

#182 Clean deps
  CHANGELOG.md
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: roadmap

#184 Make setup.py executable and include templates in dist
  MANIFEST.in
  setup.py
Labels: meta, roadmap

#183 Deprecate sphinx docs
  README.md
  docs/asgi.rst
  docs/bindables.rst
  docs/conf.py
  docs/documenting-schema.rst
  docs/enums.rst
  docs/error-messaging.rst
  docs/index.rst
  docs/integrations.rst
  docs/interfaces.rst
  docs/introduction.rst
  docs/local-development.rst
  docs/logging.rst
  docs/logo.rst
  docs/modularization.rst
  docs/mutations.rst
  docs/resolvers.rst
  docs/scalars.rst
  docs/subscriptions.rst
  docs/unions.rst
  docs/wsgi.rst
Labels: docs, meta, roadmap
