Repository mirumee/ariadne, pull requests merged in 2019-10, with the labels that each got.

#250 Add test case for unused directive being defined in schema
  tests/test_directives.py
Labels: enhancement

#252 Update changelog to include version 0.7.0
  CHANGELOG.md
Labels: meta

#254 Add schema validation to make_executable_schema
  ariadne/executable_schema.py
  tests/test_executable_schema_validation.py
Labels: enhancement, hacktoberfest
