Repository mirumee/ariadne, pull requests merged in 2019-04, with the labels that each got.

#117 Library API cleanup
  CHANGELOG.md
  README.md
  ariadne/__init__.py
  ariadne/enums.py
  ariadne/executable_schema.py
  ariadne/interfaces.py
  ariadne/objects.py
  ariadne/resolvers.py
  ariadne/scalars.py
  ariadne/subscriptions.py
  ariadne/types.py
  ariadne/unions.py
  docs/bindables.rst
  docs/custom-server.rst
  docs/enums.rst
  docs/index.rst
  docs/interfaces.rst
  docs/introduction.rst
  docs/modularization.rst
  docs/mutations.rst
  docs/resolvers.rst
  docs/scalars.rst
  docs/subscriptions.rst
  docs/unions.rst
  docs/wsgi.rst
  tests/conftest.py
  tests/test_custom_scalars.py
  tests/test_enums.py
  tests/test_fallback_resolvers.py
  tests/test_interfaces.py
  tests/test_modularization.py
  tests/test_mutations.py
  tests/test_objects.py
  tests/test_queries.py
  tests/test_resolver_map.py
  tests/test_subscriptions.py
  tests/test_unions.py
  tests/wsgi/test_custom_middleware.py
Labels: critical, enhancement, roadmap

#129 Update changelog and regenerate dependencies
  CHANGELOG.md
  requirements-dev.in
  requirements-dev.txt
Labels: docs

#131 Setup black to ignore tests snapshots
  ariadne/scalars.py
  ariadne/wsgi.py
  pyproject.toml
Labels: meta

#128 Improve error reporting
  CHANGELOG.md
  README.md
  ariadne/__init__.py
  ariadne/asgi.py
  ariadne/format_errors.py
  ariadne/types.py
  ariadne/wsgi.py
  docs/error-messaging.rst
  docs/introduction.rst
  tests/asgi/test_configuration.py
  tests/conftest.py
  tests/test_error_formatting.py
  tests/wsgi/test_configuration.py
Labels: enhancement, roadmap

#132 Update readme's self-promotion bits
  README.md
Labels: meta

#134 Handle exceptions occuring during context repr() creation
  ariadne/format_errors.py
  tests/test_error_formatting.py
Labels: enhancement

#133 Base server implementation, Django integration example
  CHANGELOG.md
  ariadne/__init__.py
  ariadne/asgi.py
  ariadne/graphql.py
  ariadne/types.py
  ariadne/wsgi.py
  docs/custom-server.rst
  docs/wsgi.rst
  requirements-dev.in
  requirements-dev.txt
  tests/asgi/snapshots/snap_test_query_execution.py
  tests/asgi/snapshots/snap_test_request_data_reading.py
  tests/test_graphql.py
  tests/wsgi/conftest.py
  tests/wsgi/snapshots/snap_test_query_execution.py
  tests/wsgi/test_custom_middleware.py
  tests/wsgi/test_http_error_handling.py
  tests/wsgi/test_request_dispatching.py
Labels: critical, enhancement, roadmap

#145 Remove dependency on typing package
  CHANGELOG.md
  docs/conf.py
  requirements.txt
  setup.py
Labels: enhancement

#146 Get rid of the unnecessary character from the sample code
  docs/mutations.rst
Labels: docs
