Repository mirumee/ariadne, pull requests merged in 2019-03, with the labels that each got.

#114 Fix pylint errors introduced by recent PyLint
  tests/wsgi/test_request_dispatching.py
Labels: enhancement

#112 Add interfaces
  CHANGELOG.md
  README.md
  ariadne/__init__.py
  ariadne/interfaces.py
  ariadne/resolvers.py
  docs/index.rst
  docs/interfaces.rst
  docs/unions.rst
  tests/test_interfaces.py
  tests/test_unions.py
Labels: enhancement, roadmap

#105 Document Ariadne's support for Descriptions [initial draft]
  docs/_static/graphql-playground-example.jpg
  docs/documenting-schema.rst
  docs/index.rst
Labels: docs, enhancement, roadmap
