Repository mirumee/ariadne, pull requests merged in 2019-01, with the labels that each got.

#85 Add features list to readme and docs index
  README.md
  docs/index.rst
Labels: docs, meta

#86 Bump version to 0.2.0 and add release date to changelog
  CHANGELOG.md
  setup.py
Labels: meta

#90 Support transforming enum values to internal representation
  CHANGELOG.md
  ariadne/__init__.py
  ariadne/enums.py
  docs/enums.rst
  tests/test_enums.py
Labels: enhancement, roadmap

#94 Fix typo in README
  README.md
Labels: bug, meta

#96 Update Django integration docs
  docs/custom-server.rst
Labels: docs

#99 Upgrade Playground to 1.8.7
  CHANGELOG.md
  ariadne/constants.py
  tests/wsgi_middleware/snapshots/snap_test_playground.py
Labels: enhancement
