Repository mirumee/ariadne, pull requests merged in 2019-08, with the labels that each got.

#225 Fix sub complete
  CHANGELOG.md
  ariadne/asgi.py
Labels: bug, enhancement

#228 Await callable context value in ASGI
  CHANGELOG.md
  ariadne/asgi.py
  tests/asgi/test_configuration.py
Labels: bug

#215 Add tracing extensions
  CHANGELOG.md
  README.md
  ariadne/asgi.py
  ariadne/contrib/tracing/__init__.py
  ariadne/contrib/tracing/apollotracing.py
  ariadne/contrib/tracing/opentracing.py
  ariadne/contrib/tracing/utils.py
  ariadne/extensions.py
  ariadne/graphql.py
  ariadne/types.py
  requirements-dev.in
  requirements-dev.txt
  tests/asgi/test_configuration.py
  tests/conftest.py
  tests/test_extensions.py
  tests/tracing/__init__.py
  tests/tracing/snapshots/__init__.py
  tests/tracing/snapshots/snap_test_apollotracing.py
  tests/tracing/test_apollotracing.py
  tests/tracing/test_opentracing.py
  tests/tracing/test_utils.py
Labels: roadmap

#230 Sync middleware implementation with extensions
  CHANGELOG.md
  ariadne/asgi.py
  ariadne/extensions.py
  ariadne/wsgi.py
  tests/asgi/test_configuration.py
  tests/asgi/test_query_execution.py
  tests/wsgi/test_configuration.py
Labels: enhancement

#233 Gitignore pip-wheel-metadata
  .gitignore
Labels: dependencies, meta

#232 Update dependencies
  requirements-dev.txt
  requirements.txt
  setup.py
  tests/test_schema_file_load.py
  tests/tracing/snapshots/snap_test_apollotracing.py
  tests/tracing/test_apollotracing.py
Labels: dependencies

#234 Make error formatting utils public
  CHANGELOG.md
  ariadne/__init__.py
  ariadne/format_error.py
  tests/test_error_formatting.py
Labels: enhancement, roadmap

#238 Add docs repo url to readme
  README.md
Labels: meta

#222 Feature - Schema directives visitor
  ariadne/__init__.py
  ariadne/executable_schema.py
  ariadne/schema_visitor.py
  tests/test_directives.py
  tests/test_schema_visitor.py
Labels: enhancement, roadmap
