Repository mirumee/ariadne, pull requests merged in 2021-03, with the labels that each got.

#465 Added support for numbers in camelCase variables.
  ariadne/utils.py
  tests/test_case_convertion_util.py
Labels: enhancement

#480 Update GraphQL core to latest version
  CHANGELOG.md
  ariadne/asgi.py
  ariadne/contrib/federation/utils.py
  ariadne/schema_visitor.py
  requirements.txt
Labels: dependencies, roadmap

#481 Fix #442, append underscore when word is followed by digits
  ariadne/utils.py
  tests/test_camel_case_to_snake_case_convertion.py
Labels: enhancement

#484 Replace Travis-CI with GitHub actions
  .github/workflows/tests.yml
  .travis.yml
  README.md
  requirements-dev-py39.txt
Labels: meta

#489 Fix dev deps for Python 3.9
  .github/workflows/tests.yml
  requirements-dev-py39.txt
  requirements-dev.txt
Labels: enhancement

#490 Bump version to 0.13, add changelog
  CHANGELOG.md
  setup.py
Labels: meta

#499 Fix #478: Update links to point to GitHub discussions
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  readthedocs.yml
Labels: meta

#488 Add on_connect/on_disconnect hooks to ASGI app, support connection context
  CHANGELOG.md
  ariadne/asgi.py
  tests/asgi/test_websockets.py
Labels: enhancement, roadmap
