Repository mirumee/ariadne, pull requests merged in 2022-11, with the labels that each got.

#962 fix 516: add support for passing through Logger or LoggerAdapter instance
  CHANGELOG.md
  ariadne/asgi/graphql.py
  ariadne/asgi/handlers/base.py
  ariadne/graphql.py
  ariadne/logger.py
  tests/asgi/test_configuration.py
  tests/wsgi/test_configuration.py
Labels: enhancement

#960 fix 876: add support for @tag federation v1 directive
  ariadne/contrib/federation/schema.py
  tests/federation/test_schema.py
Labels: enhancement

#964 Update workflows
  .github/workflows/publish.yml
  .github/workflows/tests.yml
Labels: meta

#970 Auto-run tests suite bi-weekly to catch eventual dependency breaks
  .github/workflows/tests.yml
Labels: meta

#971 Fix mypy errors on master
  .github/workflows/tests.yml
  ariadne/asgi/graphql.py
  ariadne/asgi/handlers/base.py
  ariadne/asgi/handlers/graphql_transport_ws.py
  ariadne/asgi/handlers/graphql_ws.py
  ariadne/asgi/handlers/http.py
  ariadne/contrib/tracing/apollotracing.py
  ariadne/contrib/tracing/opentracing.py
  ariadne/exceptions.py
  ariadne/explorer/apollo.py
  ariadne/explorer/graphiql.py
  ariadne/explorer/playground.py
  ariadne/explorer/template.py
  ariadne/extensions.py
  ariadne/resolvers.py
  ariadne/schema_visitor.py
  ariadne/types.py
  ariadne/validation/query_cost.py
Labels: enhancement

#973 Fix python 3.7 build
  pyproject.toml
  tests/test_dataloaders.py
Labels: critical

#979 Add Python 3.11 to build matrix
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  ariadne/contrib/tracing/opentracing.py
  ariadne/wsgi.py
  pyproject.toml
  tests/tracing/test_opentracing_sync.py
  tests/wsgi/factories.py
  tests/wsgi/snapshots/snap_test_query_execution.py
  tests/wsgi/test_query_execution.py
  tests/wsgi/test_request_data_reading.py
Labels: enhancement, meta

#980 Add execution_context_class option to ASGI and WSGI apps
  CHANGELOG.md
  ariadne/asgi/graphql.py
  ariadne/asgi/handlers/base.py
  ariadne/asgi/handlers/http.py
  ariadne/wsgi.py
  tests/wsgi/test_configuration.py
Labels: enhancement

#983 Tweak middleware options
  CHANGELOG.md
  ariadne/asgi/handlers/base.py
  ariadne/asgi/handlers/http.py
  ariadne/extensions.py
  ariadne/graphql.py
  ariadne/types.py
  ariadne/wsgi.py
Labels: enhancement
